name: Test Release

on: [push, pull_request, workflow_dispatch]

jobs:
  test-semantic-latest:
    name: test-semantic-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          dry_run: true
          branches: |
            [
              'main',
              'release',
              'develop'
            ]
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Test Outputs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
